name: Releases

on: 
  push:
    tags:
    - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv
    - run: devenv shell release-github
      name: Release on Github
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/map-card.js"
        generateReleaseNotes: true
